select
    project_id,
    event_id,
    entity_id,
    project_name,
    event_type,
    try_cast(announcement_date as date) as announcement_date,
    try_cast(period_start as date) as period_start,
    try_cast(period_end as date) as period_end,
    try_cast(planned_start as varchar) as planned_start,
    try_cast(production_start as varchar) as production_start,
    facility_id,
    location,
    product,
    technology,
    status,
    capacity_metric,
    try_cast(capacity_before as double) as capacity_before,
    try_cast(capacity_after as double) as capacity_after,
    try_cast(capacity_change as double) as capacity_change,
    capacity_unit,
    case when capex_plan is null then null else try_cast(capex_plan.low as double) end as capex_plan_low,
    case when capex_plan is null then null else try_cast(capex_plan.high as double) end as capex_plan_high,
    case when capex_plan is null then currency else coalesce(capex_plan.currency, currency) end as capex_currency,
    case when capex_plan is null then null else capex_plan.scale end as capex_scale,
    demand_evidence,
    funding_source,
    subsidy,
    debt,
    customer_commitment,
    customer_deposit,
    orders_backlog_reference,
    quality_flag,
    source_system,
    source_doc_id,
    source_url,
    provenance,
    'gold' as data_layer
from {{ ref('silver_capex_projects') }}
where quality_flag = 'primary_source_extracted'
  and nullif(trim(source_doc_id), '') is not null
  and nullif(trim(source_url), '') is not null
