select
    capex.project_id,
    capex.entity_id,
    capex.project_name,
    capex.event_type,
    capex.announcement_date,
    capex.period_start as capex_period_start,
    capex.period_end as capex_period_end,
    capex.product,
    capex.technology,
    capex.status as capex_status,
    capex.capacity_metric,
    capex.capacity_before,
    capex.capacity_after,
    capex.capacity_change,
    capex.capacity_unit,
    capex.capex_plan_low,
    capex.capex_plan_high,
    capex.capex_currency,
    capex.capex_scale,
    capex.demand_evidence,
    capex.customer_commitment,
    capex.source_doc_id as capex_source_doc_id,
    capex.source_url as capex_source_url,
    revenue.latest_annual_period_end,
    revenue.latest_annual_fiscal_year,
    revenue.latest_annual_revenue,
    revenue.latest_annual_revenue_unit,
    revenue.latest_annual_source_url,
    revenue.latest_quarter_period_end,
    revenue.latest_quarter_fiscal_year,
    revenue.latest_quarter_fiscal_period,
    revenue.latest_quarter_revenue,
    revenue.latest_quarter_revenue_unit,
    revenue.latest_quarter_source_url,
    'gold' as data_layer,
    'gold' as publication_tier
from {{ ref('gold_capex_projects') }} as capex
left join {{ ref('gold_company_revenue_latest') }} as revenue
    on capex.entity_id = revenue.entity_id
